### PR TITLE
fix: remove user stories

### PR DESCRIPTION
**Pull request by moT01**
Related to: https://github.com/freeCodeCamp/freeCodeCamp/issues/39721

Wait to merge until user stories are on /learn

### CODE REVIEW

**Comment by Sky020** [comment]
Potentially remove hyperdev from this in this PR?

**Comment by moT01** [comment]
I would really love to - I feel like we should either have a discussion on the current issue about what else to change, or perhaps just leave it for another issue.

I want to:
- Change the favicons
- Make all the titles uniform
- Make a uniform layout where we can - basically just have the project title and an hr
- Remove old assets like you mentioned (glitch/hyperdev, .gitconfig file)
- Create a .gitignore with a few things in it

I'll post something on the issue

**Comment by RandellDawson** [comment]
@moT01 Like was done on https://github.com/freeCodeCamp/boilerplate-project-urlshortener/pull/23, we have not been including mongodb and mongoose, to allow the user to install whatever versions they want to work with.  In general, we want to keep the [package.json](https://github.com/freeCodeCamp/boilerplate-project-urlshortener/blob/f091da64e954ac5087ff29e7fad8f3f367de74c9/package.json) as minimal as possible.

**Review by Sky020 — APPROVED** [review]
This LGTM 👍

**Comment by Sky020** [comment]
@RandellDawson The `/learn` changes are on production: https://github.com/freeCodeCamp/freeCodeCamp/commits/production-current

If you are happy with this, we can merge.

**Review by nhcarrigan — APPROVED** [review]
LGTM~! 🥳 

Thank you for your pull request! We look forward to additional contributions!

**Pull request merged**
