### PR TITLE
Project refactor

### PR DESCRIPTION
**Pull request by shemuelx**
Refactor: major layout project structure changes.

### CODE REVIEW

**Comment by gikf** [comment]
Hey @shemuelx

Looks like this PR was supposed to be made on your own fork, instead of the original boilerplate repository.

This is a standard message notifying you that we've reviewed your pull request and have decided not to merge it. We would welcome future pull requests from you.

Thank you and happy coding.

**Comment by shemuelx** [comment]
Hi @gikf! 

I'm sorry! Was a mistake.  I'm willing to contribute to freeCodecamp!

Thank you! Gracias! And happy coding too.

**Comment by shemuelx** [comment]
Hi again gikf!

I hope you will be fine. I would like to contribute. Do you know some appropriate issue for me? 

Thank you in advance! Happy coding!

Gracias/Obrigado

**Comment by gikf** [comment]
Hey,

if you want to contribute to freeCodeCamp, please check https://contribute.freecodecamp.org/intro/

**Happy Contributing!** 🌟

**Pull request closed without merging**
