### PR TITLE
Add user stories to readme

### PR DESCRIPTION
**Pull request by energydev**
Adding user stories to the readme per guidance from the below issue.

https://github.com/freeCodeCamp/freeCodeCamp/issues/17998

### CODE REVIEW

**Comment by jMuzsik** [comment]
@raisedadead or someone else, this should be accepted. Maybe, @amandeepmittal

**Comment by amandeepmittal** [comment]
@jMuzsik I do not have write access to the repo. Maybe @QuincyLarson can help.

**Comment by raisedadead** [comment]
Hi @amandeepmittal I have added you the Github moderators team. You should be able to merge PRs in most repos.

Thanks @energydev for taking the the time to prepare this PR. Thanks @jMuzsik and @amandeepmittal for the QA.

**Comment by amandeepmittal** [comment]
@raisedadead Thanks a lot!

**Pull request merged**
